<a href="https://colab.research.google.com/github/fani-lab/Adila/blob/main/quickstart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---

**Setup Python 3.8 in Colab**
- No need to create an environment as we are already in an environment/container


---

In [1]:
!sudo apt-get update -y
!sudo apt-get install -y python3.8 python3.8-venv python3.8-distutils python3-pip
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 10
!python --version

Hit:1 https://cli.github.com/packages stable InRelease
Get:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:4 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [2,201 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:11 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [83.6 kB]
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:13 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,519 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:15 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,844 kB]
Get:16 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.5 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,081 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,287 kB]
Get:19 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,573 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [3,904 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,598 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [6,287 kB]
Fetched 37.8 MB in 8s (4,949 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  javascript-common libjs-sphinxdoc libjs-underscore libpython3.10
  libpython3.10-dev libpython3.10-minimal libpython3.10-stdlib
  libpython3.8-minimal libpython3.8-stdlib python3-dev python3-pkg-resources
  python3-setuptools python3-wheel python3.10 python3.10-dev
  python3.10-minimal python3.8-lib2to3 python3.8-minimal
Suggested packages:
  apache2 | lighttpd | httpd python-setuptools-doc python3.10-venv
  python3.10-doc binfmt-support
The following NEW packages will be installed:
  javascript-common libjs-sphinxdoc libjs-underscore libpython3.8-minimal
  libpython3.8-stdlib python3-dev python3-pip python3-setuptools python3-wheel
  python3.10-dev python3.8 python3.8-distutils python3.8-lib2to3
  python3.8-minimal python3.8-venv
The following packages will be upgraded:
  libpython3.10 libpython3.10-dev libpython3.10-minimal libpython3.10-stdlib
  python3-pkg-resources python3.10 python3.10-minimal
7 upgraded, 15 newly installed, 0 to remove and 65 not upgraded.
Need to get 23.0 MB of archives.
After this operation, 33.8 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10-dev amd64 3.10.12-1~22.04.12 [4,763 kB]
Get:2 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 libpython3.8-minimal amd64 3.8.20-1+jammy1 [796 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10 amd64 3.10.12-1~22.04.12 [1,949 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3.10 amd64 3.10.12-1~22.04.12 [508 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10-stdlib amd64 3.10.12-1~22.04.12 [1,849 kB]
Get:6 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 python3.8-minimal amd64 3.8.20-1+jammy1 [2,023 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3.10-minimal amd64 3.10.12-1~22.04.12 [2,268 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10-minimal amd64 3.10.12-1~22.04.12 [815 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 javascript-common all 11+nmu1 [5,936 B]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libjs-underscore all 1.13.2~dfsg-2 [118 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 libjs-sphinxdoc all 4.3.2-1 [139 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3.10-dev amd64 3.10.12-1~22.04.12 [508 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3-dev amd64 3.10.6-1~22.04.1 [26.0 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 python3-wheel all 0.37.1-2ubuntu0.22.04.1 [32.0 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 python3-pip all 22.0.2+dfsg-1ubuntu0.7 [1,306 kB]
Get:16 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 libpython3.8-stdlib amd64 3.8.20-1+jammy1 [1,817 kB]
Get:17 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy/main amd64 python3-pkg-resources all 68.1.2-2~jammy3 [216 kB]
Get:18 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy/main amd64 python3-setuptools all 68.1.2-2~jammy3 [465 kB]
Get:19 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 python3.8 amd64 3.8.20-1+jammy1 [440 kB]
Get:20 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 python3.8-lib2to3 all 3.8.20-1+jammy1 [126 kB]
Get:21 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 python3.8-distutils all 3.8.20-1+jammy1 [193 kB]
Get:22 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 python3.8-venv amd64 3.8.20-1+jammy1 [2,618 kB]
Fetched 23.0 MB in 23s (993 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 22.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
(Reading database ... 121713 files and directories currently installed.)
Preparing to unpack .../00-libpython3.10-dev_3.10.12-1~22.04.12_amd64.deb ...
Unpacking libpython3.10-dev:amd64 (3.10.12-1~22.04.12) over (3.10.12-1~22.04.11) ...
Preparing to unpack .../01-libpython3.10_3.10.12-1~22.04.12_amd64.deb ...
Unpacking libpython3.10:amd64 (3.10.12-1~22.04.12) over (3.10.12-1~22.04.11) ...
Preparing to unpack .../02-python3.10_3.10.12-1~22.04.12_amd64.deb ...
Unpacking python3.10 (3.10.12-1~22.04.12) over (3.10.12-1~22.04.11) ...
Preparing to unpack .../03-libpython3.10-stdlib_3.10.12-1~22.04.12_amd64.deb ...
Unpacking libpython3.10-stdlib:amd64 (3.10.12-1~22.04.12) over (3.10.12-1~22.04.11) ...
Preparing to unpack .../04-python3.10-minimal_3.10.12-1~22.04.12_amd64.deb ...
Unpacking python3.10-minimal (3.10.12-1~22.04.12) over (3.10.12-1~22.04.11) ...
Preparing to unpack .../05-libpython3.10-minimal_3.10.12-1~22.04.12_amd64.deb ...
Unpacking libpython3.10-minimal:amd64 (3.10.12-1~22.04.12) over (3.10.12-1~22.04.11) ...
Selecting previously unselected package libpython3.8-minimal:amd64.
Preparing to unpack .../06-libpython3.8-minimal_3.8.20-1+jammy1_amd64.deb ...
Unpacking libpython3.8-minimal:amd64 (3.8.20-1+jammy1) ...
Selecting previously unselected package python3.8-minimal.
Preparing to unpack .../07-python3.8-minimal_3.8.20-1+jammy1_amd64.deb ...
Unpacking python3.8-minimal (3.8.20-1+jammy1) ...
Selecting previously unselected package javascript-common.
Preparing to unpack .../08-javascript-common_11+nmu1_all.deb ...
Unpacking javascript-common (11+nmu1) ...
Selecting previously unselected package libjs-underscore.
Preparing to unpack .../09-libjs-underscore_1.13.2~dfsg-2_all.deb ...
Unpacking libjs-underscore (1.13.2~dfsg-2) ...
Selecting previously unselected package libjs-sphinxdoc.
Preparing to unpack .../10-libjs-sphinxdoc_4.3.2-1_all.deb ...
Unpacking libjs-sphinxdoc (4.3.2-1) ...
Selecting previously unselected package libpython3.8-stdlib:amd64.
Preparing to unpack .../11-libpython3.8-stdlib_3.8.20-1+jammy1_amd64.deb ...
Unpacking libpython3.8-stdlib:amd64 (3.8.20-1+jammy1) ...
Selecting previously unselected package python3.10-dev.
Preparing to unpack .../12-python3.10-dev_3.10.12-1~22.04.12_amd64.deb ...
Unpacking python3.10-dev (3.10.12-1~22.04.12) ...
Selecting previously unselected package python3-dev.
Preparing to unpack .../13-python3-dev_3.10.6-1~22.04.1_amd64.deb ...
Unpacking python3-dev (3.10.6-1~22.04.1) ...
Preparing to unpack .../14-python3-pkg-resources_68.1.2-2~jammy3_all.deb ...
Unpacking python3-pkg-resources (68.1.2-2~jammy3) over (59.6.0-1.2ubuntu0.22.04.3) ...
Selecting previously unselected package python3-setuptools.
Preparing to unpack .../15-python3-setuptools_68.1.2-2~jammy3_all.deb ...
Unpacking python3-setuptools (68.1.2-2~jammy3) ...
Selecting previously unselected package python3-wheel.
Preparing to unpack .../16-python3-wheel_0.37.1-2ubuntu0.22.04.1_all.deb ...
Unpacking python3-wheel (0.37.1-2ubuntu0.22.04.1) ...
Selecting previously unselected package python3-pip.
Preparing to unpack .../17-python3-pip_22.0.2+dfsg-1ubuntu0.7_all.deb ...
Unpacking python3-pip (22.0.2+dfsg-1ubuntu0.7) ...
Selecting previously unselected package python3.8.
Preparing to unpack .../18-python3.8_3.8.20-1+jammy1_amd64.deb ...
Unpacking python3.8 (3.8.20-1+jammy1) ...
Selecting previously unselected package python3.8-lib2to3.
Preparing to unpack .../19-python3.8-lib2to3_3.8.20-1+jammy1_all.deb ...
Unpacking python3.8-lib2to3 (3.8.20-1+jammy1) ...
Selecting previously unselected package python3.8-distutils.
Preparing to unpack .../20-python3.8-distutils_3.8.20-1+jammy1_all.deb ...
Unpacking python3.8-distutils (3.8.20-1+jammy1) ...
Selecting previously unselected package python3.8-venv.
Preparing to unpack .../21-python3.8-venv_3.8.20-1+jammy1_amd64.deb ...
Unpacking python3.8-venv (3.8.20-1+jammy1) ...
Setting up python3-pkg-resources (68.1.2-2~jammy3) ...
Setting up javascript-common (11+nmu1) ...
Setting up libpython3.8-minimal:amd64 (3.8.20-1+jammy1) ...
Setting up python3-setuptools (68.1.2-2~jammy3) ...
Setting up python3-wheel (0.37.1-2ubuntu0.22.04.1) ...
Setting up python3.8-lib2to3 (3.8.20-1+jammy1) ...
Setting up libpython3.10-minimal:amd64 (3.10.12-1~22.04.12) ...
Setting up python3-pip (22.0.2+dfsg-1ubuntu0.7) ...
Setting up python3.8-minimal (3.8.20-1+jammy1) ...
Setting up python3.8-distutils (3.8.20-1+jammy1) ...
Setting up libpython3.8-stdlib:amd64 (3.8.20-1+jammy1) ...
Setting up python3.8 (3.8.20-1+jammy1) ...
Setting up libjs-underscore (1.13.2~dfsg-2) ...
Setting up python3.10-minimal (3.10.12-1~22.04.12) ...
Setting up libpython3.10-stdlib:amd64 (3.10.12-1~22.04.12) ...
Setting up python3.8-venv (3.8.20-1+jammy1) ...
Setting up libjs-sphinxdoc (4.3.2-1) ...
Setting up libpython3.10:amd64 (3.10.12-1~22.04.12) ...
Setting up python3.10 (3.10.12-1~22.04.12) ...
Setting up libpython3.10-dev:amd64 (3.10.12-1~22.04.12) ...
Setting up python3.10-dev (3.10.12-1~22.04.12) ...
Setting up python3-dev (3.10.6-1~22.04.1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
update-alternatives: using /usr/bin/python3.8 to provide /usr/bin/python3 (python3) in auto mode
Python 3.8.20

In [2]:
!rm -R adila/
!git clone https://github.com/Fani-Lab/adila
!pip install --upgrade pip setuptools
!pip install -r adila/requirements.txt

rm: cannot remove 'adila/': No such file or directory
Cloning into 'adila'...
remote: Enumerating objects: 1703, done.
remote: Counting objects: 100% (261/261), done.
remote: Compressing objects: 100% (155/155), done.
remote: Total 1703 (delta 156), reused 143 (delta 88), pack-reused 1442 (from 2)
Receiving objects: 100% (1703/1703), 17.49 MiB | 18.02 MiB/s, done.
Resolving deltas: 100% (909/909), done.
Requirement already satisfied: pip in /usr/lib/python3/dist-packages (22.0.2)
Collecting pip
  Downloading pip-25.0.1-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 18.9 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (68.1.2)
Collecting setuptools
  Downloading setuptools-75.3.2-py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 9.5 MB/s eta 0:00:00
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 68.1.2
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'setuptools'. No files were found to uninstall.
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-25.0.1 setuptools-75.3.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Collecting hydra-core==1.3.2 (from -r adila/requirements.txt (line 1))
  Downloading hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Collecting numpy==1.24.4 (from -r adila/requirements.txt (line 2))
  Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Collecting omegaconf<2.4,>=2.2 (from hydra-core==1.3.2->-r adila/requirements.txt (line 1))
  Downloading omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
Collecting antlr4-python3-runtime==4.9.* (from hydra-core==1.3.2->-r adila/requirements.txt (line 1))
  Downloading antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
  Preparing metadata (setup.py) ... done
Collecting packaging (from hydra-core==1.3.2->-r adila/requirements.txt (line 1))
  Downloading packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Collecting importlib-resources (from hydra-core==1.3.2->-r adila/requirements.txt (line 1))
  Downloading importlib_resources-6.4.5-py3-none-any.whl.metadata (4.0 kB)
Collecting PyYAML>=5.1.0 (from omegaconf<2.4,>=2.2->hydra-core==1.3.2->-r adila/requirements.txt (line 1))
  Downloading PyYAML-6.0.3-cp38-cp38-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.1 kB)
Collecting zipp>=3.1.0 (from importlib-resources->hydra-core==1.3.2->-r adila/requirements.txt (line 1))
  Downloading zipp-3.20.2-py3-none-any.whl.metadata (3.7 kB)
Downloading hydra_core-1.3.2-py3-none-any.whl (154 kB)
Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 124.2 MB/s eta 0:00:00
Downloading omegaconf-2.3.0-py3-none-any.whl (79 kB)
Downloading importlib_resources-6.4.5-py3-none-any.whl (36 kB)
Downloading packaging-25.0-py3-none-any.whl (66 kB)
Downloading PyYAML-6.0.3-cp38-cp38-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (806 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 806.0/806.0 kB 40.9 MB/s eta 0:00:00
Downloading zipp-3.20.2-py3-none-any.whl (9.2 kB)
Building wheels for collected packages: antlr4-python3-runtime
  Building wheel for antlr4-python3-runtime (setup.py) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144552 sha256=64d331d6e28c1516b48f3dc8b1dd3fa67b111df6c8608b4de15999171a942315
  Stored in directory: /root/.cache/pip/wheels/b1/a3/c2/6df046c09459b73cc9bb6c4401b0be6c47048baf9a1617c485
Successfully built antlr4-python3-runtime
Installing collected packages: antlr4-python3-runtime, zipp, PyYAML, packaging, numpy, omegaconf, importlib-resources, hydra-core
  Attempting uninstall: zipp
    Found existing installation: zipp 1.0.0
    Uninstalling zipp-1.0.0:
      Successfully uninstalled zipp-1.0.0
Successfully installed PyYAML-6.0.3 antlr4-python3-runtime-4.9.3 hydra-core-1.3.2 importlib-resources-6.4.5 numpy-1.24.4 omegaconf-2.3.0 packaging-25.0 zipp-3.20.2



---


**1. Running Adila (Single)**

[`Hydra`](https://hydra.cc/) config overriding `data.*`, `fair.*`, and `eval.*` settings in [`Adila/src/__config__.yaml`](https://github.com/fani-lab/Adila/blob/main/src/__config__.yaml)



---



  - **data.**`fteamsvecs`, the sparse matrix representation of the entire dataset (teams), including `['member']` and `['skill']`, each row showing a `team`
  - **data.**`fsplits`, the train-test split rowids of `data.fteamsvecs`
  - **data.**`fpred`, contains the member recommendations for each team in the test split, of size `|test|×|member|`. The split file is necessary to know these recommendations are for what teams in the dataset
  
  These files can be obtained from by runnig `OpeNTF` team recommendation library at [`OpeNTF`](https://github.com/fani-lab/OpeNTF) like for the `toy.dblp` dataset at [`OpeNTF/data/dblp/toy.dblp.v12.json`](https://github.com/fani-lab/OpeNTF/tree/main/data/dblp/toy.dblp.v12.json).
  
  Adila codebase already included them at [`Adila/output/dblp/toy.dblp.v12.json`](https://github.com/fani-lab/Adila/tree/main/output/dblp/toy.dblp.v12.json)
  - **data.**`fgender`, contains the `female` member ids as the `minority` also `protected` group.
  
  In `Adila`, we keep the labels of `minority` group for efficiency as they are very few relative to majority group. However, `protected` group could be the same as `minority` group, like in `gender` protected attribute, or the `majority` group (non-popular experts, who are more often than popular ones), like in `popularity` protected attribute.

  - **data.**`output`, which is the path of generated files. As seen in the codebase, it is suggested to follow same folder structure as in [`OpeNTF`](https://github.com/fani-lab/OpeNTF) to avoid conflicts between prediction files of different baselines.



```
data:
  fteamsvecs: ../output/dblp/toy.dblp.v12.json/teamsvecs.pkl
  fgender: ../output/dblp/toy.dblp.v12.json/females.csv
  fsplits: ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85.pkl
  fpred: ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred
  output: ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000
```

---

  - **fair.**`algorithm`, list of reranking algorithms from `det_greedy`, `det_cons`, `det_relaxed`, `det_const_sort`, `fa-ir`
  - **fair.**`notion`, list of notions of fairness, from equality of odds (`eo`), demographic parity (`dp`)
  - **fair.**`attribute`, list of protected attributes from `popularity`, `gender`
  - **fair.**`is_popular_alg`, popularity status based on either `avg` teams per experts, i.e., whoever above this value is popular, or `auc` whoever is in the head of distribution figure, or both
  - **fair.**`k_max`, cutoff for the reranking algorithms
  - **fair.**`alpha`, the significance value for fa-ir algorithm


```
fair:
  algorithm: [fa-ir, det_greedy]
  notion: [dp, eo]
  attribute: [popularity, gender]
  is_popular_alg: [avg, auc]
  k_max: 5
  alpha: 0.1
```
---

  - **eval.**`per_instance`, metric value for each test instance of team, needed for paired significance tests
  - **eval.**`metrics.fair`, metrics to measure fairness of the recommended members for the test teams
  - **eval.**`metrics.trec`, metrics to measure accuracy of the recommended members for the test teams using ranking metrics from `trec_eval`. See the complete list at [`pytrec_eval`](https://github.com/terrierteam/pytrec_eval/blob/master/tests/pytrec_eval_tests.py)
  - **eval.**`metrics.topk`, cutoff for the top-k recommended members

```
eval:
  per_instance: True
  metrics:
    fair: [ndkl, skew]
    topk: '2,5'
    trec: [P_topk, recall_topk, ndcg_cut_topk, map_cut_topk, success_topk]
```

In [17]:
%cd adila/src/
!python main.py data.fpred=../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred "fair.algorithm=[fa-ir, det_greedy]" "fair.notion=[dp, eo]" "fair.attribute=[popularity, gender]" "fair.is_popular_alg=[avg, auc]"

[Errno 2] No such file or directory: 'adila/src/'
/content/adila/src
[2025-12-10 04:44:27,811][adila][INFO] - Loading stats, ratios, and ids for minority experts ...
/content/adila/src/adila.py:102: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  preds = torch.load(fpred, map_location='cpu')['y_pred']
[2025-12-10 04:44:27,817][adila][INFO] - Reranking ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred using fa-ir with 5 cutoff ...
[2025-12-10 04:44:27,817][adila][INFO] - Loading reranked file ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.fa-ir.avg.10.5.rerank.pred for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred if exists ...
[2025-12-10 04:44:27,820][adila][INFO] - Fairness evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.fa-ir.avg.10.5.rerank.pred using ['ndkl', 'skew'] with 5 cutoff ...
5it [00:00, 2912.71it/s]
[2025-12-10 04:44:27,835][adila][INFO] - Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.fair.mean/instance.csv.
[2025-12-10 04:44:27,845][adila][INFO] - Utility evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.fa-ir.avg.10.5.rerank.pred ...
[2025-12-10 04:44:27,845][adila][INFO] - Before: Loading ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred.eval.mean.csv ...
[2025-12-10 04:44:27,851][adila][INFO] - After: Evaluating ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.fa-ir.avg.10.5.rerank.pred ...
[2025-12-10 04:44:27,853][pkgmgr][INFO] - evl.metric not found.
[2025-12-10 04:44:27,853][pkgmgr][INFO] - Installing evl.metric...
[2025-12-10 04:44:27,913][adila][INFO] - ['P_1,2,5', 'recall_1,2,5', 'ndcg_cut_1,2,5', 'map_cut_1,2,5', 'success_1,2,5'] ...
[2025-12-10 04:44:27,919][evl.metric][INFO] - Building pytrec_eval input for 5 instances ...
100% 5/5 [00:00<00:00, 2993.79it/s]
[2025-12-10 04:44:27,935][adila][INFO] - After: Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.utility.mean.csv.
/content/adila/src/adila.py:102: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  preds = torch.load(fpred, map_location='cpu')['y_pred']
[2025-12-10 04:44:27,936][adila][INFO] - Reranking ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred using det_greedy with 5 cutoff ...
[2025-12-10 04:44:27,936][adila][INFO] - Loading reranked file ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.det_greedy.avg.5.rerank.pred for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred if exists ...
[2025-12-10 04:44:27,938][adila][INFO] - Fairness evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.det_greedy.avg.5.rerank.pred using ['ndkl', 'skew'] with 5 cutoff ...
5it [00:00, 2531.57it/s]
[2025-12-10 04:44:27,945][adila][INFO] - Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.det_greedy.avg.5.rerank.pred.eval.fair.mean/instance.csv.
[2025-12-10 04:44:27,952][adila][INFO] - Utility evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.det_greedy.avg.5.rerank.pred ...
[2025-12-10 04:44:27,952][adila][INFO] - Before: Loading ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred.eval.mean.csv ...
[2025-12-10 04:44:27,956][adila][INFO] - After: Evaluating ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.det_greedy.avg.5.rerank.pred ...
[2025-12-10 04:44:27,957][adila][INFO] - ['P_1,2,5', 'recall_1,2,5', 'ndcg_cut_1,2,5', 'map_cut_1,2,5', 'success_1,2,5'] ...
[2025-12-10 04:44:27,963][evl.metric][INFO] - Building pytrec_eval input for 5 instances ...
100% 5/5 [00:00<00:00, 3272.20it/s]
[2025-12-10 04:44:27,971][adila][INFO] - After: Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.det_greedy.avg.5.rerank.pred.eval.utility.mean.csv.
[2025-12-10 04:44:27,971][adila][INFO] - Loading stats, ratios, and ids for minority experts ...
/content/adila/src/adila.py:102: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  preds = torch.load(fpred, map_location='cpu')['y_pred']
[2025-12-10 04:44:27,974][adila][INFO] - Reranking ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred using fa-ir with 5 cutoff ...
[2025-12-10 04:44:27,974][adila][INFO] - Loading reranked file ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.fa-ir.auc.10.5.rerank.pred for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred if exists ...
[2025-12-10 04:44:27,976][adila][INFO] - Fairness evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.fa-ir.auc.10.5.rerank.pred using ['ndkl', 'skew'] with 5 cutoff ...
5it [00:00, 4331.17it/s]
[2025-12-10 04:44:27,982][adila][INFO] - Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.fa-ir.auc.10.5.rerank.pred.eval.fair.mean/instance.csv.
[2025-12-10 04:44:27,989][adila][INFO] - Utility evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.fa-ir.auc.10.5.rerank.pred ...
[2025-12-10 04:44:27,989][adila][INFO] - Before: Loading ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred.eval.mean.csv ...
[2025-12-10 04:44:27,993][adila][INFO] - After: Evaluating ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.fa-ir.auc.10.5.rerank.pred ...
[2025-12-10 04:44:27,994][adila][INFO] - ['P_1,2,5', 'recall_1,2,5', 'ndcg_cut_1,2,5', 'map_cut_1,2,5', 'success_1,2,5'] ...
[2025-12-10 04:44:28,000][evl.metric][INFO] - Building pytrec_eval input for 5 instances ...
100% 5/5 [00:00<00:00, 3015.75it/s]
[2025-12-10 04:44:28,009][adila][INFO] - After: Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.fa-ir.auc.10.5.rerank.pred.eval.utility.mean.csv.
/content/adila/src/adila.py:102: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  preds = torch.load(fpred, map_location='cpu')['y_pred']
[2025-12-10 04:44:28,010][adila][INFO] - Reranking ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred using det_greedy with 5 cutoff ...
[2025-12-10 04:44:28,010][adila][INFO] - Loading reranked file ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.det_greedy.auc.5.rerank.pred for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred if exists ...
[2025-12-10 04:44:28,012][adila][INFO] - Fairness evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.det_greedy.auc.5.rerank.pred using ['ndkl', 'skew'] with 5 cutoff ...
5it [00:00, 4758.68it/s]
[2025-12-10 04:44:28,018][adila][INFO] - Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.det_greedy.auc.5.rerank.pred.eval.fair.mean/instance.csv.
[2025-12-10 04:44:28,024][adila][INFO] - Utility evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.det_greedy.auc.5.rerank.pred ...
[2025-12-10 04:44:28,024][adila][INFO] - Before: Loading ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred.eval.mean.csv ...
[2025-12-10 04:44:28,028][adila][INFO] - After: Evaluating ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.det_greedy.auc.5.rerank.pred ...
[2025-12-10 04:44:28,030][adila][INFO] - ['P_1,2,5', 'recall_1,2,5', 'ndcg_cut_1,2,5', 'map_cut_1,2,5', 'success_1,2,5'] ...
[2025-12-10 04:44:28,035][evl.metric][INFO] - Building pytrec_eval input for 5 instances ...
100% 5/5 [00:00<00:00, 2684.53it/s]
[2025-12-10 04:44:28,044][adila][INFO] - After: Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/dp/f0.test.pred.det_greedy.auc.5.rerank.pred.eval.utility.mean.csv.
[2025-12-10 04:44:28,044][adila][INFO] - Loading stats, ratios, and ids for minority experts ...
/content/adila/src/adila.py:102: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  preds = torch.load(fpred, map_location='cpu')['y_pred']
[2025-12-10 04:44:28,047][adila][INFO] - Reranking ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred using fa-ir with 5 cutoff ...
[2025-12-10 04:44:28,047][adila][INFO] - Loading reranked file ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.avg.10.5.rerank.pred for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred if exists ...
[2025-12-10 04:44:28,049][adila][INFO] - Fairness evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.avg.10.5.rerank.pred using ['ndkl', 'skew'] with 5 cutoff ...
5it [00:00, 4526.55it/s]
[2025-12-10 04:44:28,055][adila][INFO] - Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.fair.mean/instance.csv.
[2025-12-10 04:44:28,061][adila][INFO] - Utility evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.avg.10.5.rerank.pred ...
[2025-12-10 04:44:28,061][adila][INFO] - Before: Loading ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred.eval.mean.csv ...
[2025-12-10 04:44:28,065][adila][INFO] - After: Evaluating ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.avg.10.5.rerank.pred ...
[2025-12-10 04:44:28,066][adila][INFO] - ['P_1,2,5', 'recall_1,2,5', 'ndcg_cut_1,2,5', 'map_cut_1,2,5', 'success_1,2,5'] ...
[2025-12-10 04:44:28,072][evl.metric][INFO] - Building pytrec_eval input for 5 instances ...
100% 5/5 [00:00<00:00, 3373.80it/s]
[2025-12-10 04:44:28,083][adila][INFO] - After: Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.utility.mean.csv.
/content/adila/src/adila.py:102: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  preds = torch.load(fpred, map_location='cpu')['y_pred']
[2025-12-10 04:44:28,084][adila][INFO] - Reranking ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred using det_greedy with 5 cutoff ...
[2025-12-10 04:44:28,084][adila][INFO] - Loading reranked file ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.det_greedy.avg.5.rerank.pred for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred if exists ...
[2025-12-10 04:44:28,085][adila][INFO] - Fairness evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.det_greedy.avg.5.rerank.pred using ['ndkl', 'skew'] with 5 cutoff ...
5it [00:00, 4654.13it/s]
[2025-12-10 04:44:28,092][adila][INFO] - Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.det_greedy.avg.5.rerank.pred.eval.fair.mean/instance.csv.
[2025-12-10 04:44:28,100][adila][INFO] - Utility evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.det_greedy.avg.5.rerank.pred ...
[2025-12-10 04:44:28,100][adila][INFO] - Before: Loading ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred.eval.mean.csv ...
[2025-12-10 04:44:28,105][adila][INFO] - After: Evaluating ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.det_greedy.avg.5.rerank.pred ...
[2025-12-10 04:44:28,106][adila][INFO] - ['P_1,2,5', 'recall_1,2,5', 'ndcg_cut_1,2,5', 'map_cut_1,2,5', 'success_1,2,5'] ...
[2025-12-10 04:44:28,112][evl.metric][INFO] - Building pytrec_eval input for 5 instances ...
100% 5/5 [00:00<00:00, 3321.43it/s]
[2025-12-10 04:44:28,121][adila][INFO] - After: Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.det_greedy.avg.5.rerank.pred.eval.utility.mean.csv.
[2025-12-10 04:44:28,121][adila][INFO] - Loading stats, ratios, and ids for minority experts ...
/content/adila/src/adila.py:102: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  preds = torch.load(fpred, map_location='cpu')['y_pred']
[2025-12-10 04:44:28,124][adila][INFO] - Reranking ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred using fa-ir with 5 cutoff ...
[2025-12-10 04:44:28,124][adila][INFO] - Loading reranked file ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.auc.10.5.rerank.pred for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred if exists ...
[2025-12-10 04:44:28,125][adila][INFO] - Fairness evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.auc.10.5.rerank.pred using ['ndkl', 'skew'] with 5 cutoff ...
5it [00:00, 4550.12it/s]
[2025-12-10 04:44:28,131][adila][INFO] - Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.auc.10.5.rerank.pred.eval.fair.mean/instance.csv.
[2025-12-10 04:44:28,137][adila][INFO] - Utility evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.auc.10.5.rerank.pred ...
[2025-12-10 04:44:28,138][adila][INFO] - Before: Loading ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred.eval.mean.csv ...
[2025-12-10 04:44:28,142][adila][INFO] - After: Evaluating ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.auc.10.5.rerank.pred ...
[2025-12-10 04:44:28,143][adila][INFO] - ['P_1,2,5', 'recall_1,2,5', 'ndcg_cut_1,2,5', 'map_cut_1,2,5', 'success_1,2,5'] ...

**Output Folders and Files**

- `adila/{popularity,gender}/stats.pkl`, the distribution of popular/non-popular, or male/female experts in the entire dataset
- `adila/{popularity,gender}/labels.csv`, the ids for popular or female experts. While the female ids are fixed and obtained from the `data.fgender` file, the popular ids depends on `is_popular_alg` and is calculated based on the data distribution

- `adila/{popularity,gender}/{notion}`, the subfolder containg the results based on the fairness notion
- `adila/{popularity,gender}/{notion}/{data.fpred}.{fair.algorithm}.{fair.k_max}.rerank.pred`, the reranked version of the recommended members from `data.fpred`
- `adila/{popularity,gender}/{notion}/{data.fpred}.{fair.algorithm}.{fair.k_max}.rerank.pred.eval.fair.instance.csv`, the fairness metric values for `data.fpred` (before) and the reranked version (after) per each team instance in the test set  
- `adila/{popularity,gender}/{notion}/{data.fpred}.{fair.algorithm}.{fair.k_max}.rerank.pred.eval.fair.mean.csv`, the average of fairness metric values for `data.fpred` (before) and the reranked version (after) over all teams of the test set  
- `adila/{popularity,gender}/{notion}/{data.fpred}.{fair.algorithm}.{fair.k_max}.rerank.pred.eval.utility.instance.csv`, the accuracy metric values for `data.fpred` (before) and the reranked version (after) per each team instance in the test set  
- `adila/{popularity,gender}/{notion}/{data.fpred}.{fair.algorithm}.{fair.k_max}.rerank.pred.eval.utility.mean.csv`, the average of accuracy metric values for `data.fpred` (before) and the reranked version (after) over all teams of the test set

In [4]:
!find ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/ -print | sed 's;[^/]*/;│   ;g;s;│   \([^│]\);├── \1;'

│   │   │   │   │   │   │
│   │   │   │   │   │   ├── gender
│   │   │   │   │   │   │   ├── dp
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.10.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.10.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.10.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.10.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.10.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   ├── eo
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.10.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.10.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.10.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.10.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.10.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.5.rerank.pred
│   │   │   │   │   │   │   │   ├── ratios.pkl
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   ├── labels.csv
│   │   │   │   │   │   │   ├── stats.pkl
│   │   │   │   │   │   ├── popularity
│   │   │   │   │   │   │   ├── dp
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.auc.10.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.avg.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.auc.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.avg.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.avg.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.auc.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.avg.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.avg.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.auc.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.auc.10.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.auc.10.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.auc.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.avg.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.auc.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.avg.10.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.avg.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.auc.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.avg.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.auc.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.avg.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.auc.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.avg.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.avg.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.auc.10.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.auc.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.auc.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.auc.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.avg.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.auc.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.auc.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.avg.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.avg.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.auc.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.auc.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.avg.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.avg.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.auc.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.avg.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.auc.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.auc.10.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.avg.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.auc.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.avg.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.auc.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.avg.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.auc.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   ├── eo
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.auc.10.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.avg.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.auc.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.avg.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.avg.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.auc.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.avg.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.avg.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.auc.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.auc.10.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.auc.10.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.auc.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.avg.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.auc.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.avg.10.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.avg.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.auc.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.avg.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.auc.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.avg.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.auc.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.avg.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.avg.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.auc.10.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.auc.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.auc.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.auc.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.avg.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── ratios.pkl
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.auc.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.auc.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.avg.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.avg.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.auc.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.auc.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.avg.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.avg.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.auc.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.avg.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.auc.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.fa-ir.auc.10.5.rerank.pred
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.avg.5.rerank.pred.eval.utility.mean.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.auc.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_relaxed.avg.5.rerank.pred.eval.fair.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_cons.auc.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_greedy.avg.5.rerank.pred.eval.utility.instance.csv
│   │   │   │   │   │   │   │   ├── f0.test.pred.det_const_sort.auc.5.rerank.pred.eval.fair.mean.csv
│   │   │   │   │   │   │   ├── labels.csv
│   │   │   │   │   │   │   ├── stats.pkl
│   │   │   │   │   │   ├── p
│   │   │   │   │   │   │   ├── e

**Average fairness measures**

In [13]:
import pandas as pd
pd.read_csv('../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.fair.mean.csv', index_col=0)

                          mean
metrics
before.ndkl           0.289672
after.ndkl            0.140630
before.skew.minority -9.715486
before.skew.majority -0.028526
after.skew.minority  -9.715486
after.skew.majority  -0.028526

**Fairness measures per each test team**

In [14]:
import pandas as pd
pd.read_csv('../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.fair.instance.csv')

,before.ndkl,after.ndkl,before.skew.minority,before.skew.majority,after.skew.minority,after.skew.majority
0,0.105361,0.105361,-25.328436,0.105361,-25.328436,0.105361
1,0.105361,0.105361,-25.328436,0.105361,-25.328436,0.105361
2,0.095459,0.095459,0.693147,-0.117783,0.693147,-0.117783
3,0.943696,0.198485,0.693147,-0.117783,0.693147,-0.117783
4,0.198485,0.198485,0.693147,-0.117783,0.693147,-0.117783

**Average accuracy values (Utility)**

In [15]:
import pandas as pd
pd.read_csv('../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.utility.mean.csv', index_col = 0)

            mean.before  mean.after
metric
P_1            0.200000    0.200000
P_2            0.200000    0.200000
P_5            0.120000    0.120000
recall_1       0.100000    0.100000
recall_2       0.200000    0.200000
recall_5       0.300000    0.300000
ndcg_cut_1     0.200000    0.200000
ndcg_cut_2     0.200000    0.200000
ndcg_cut_5     0.252814    0.252814
map_cut_1      0.100000    0.100000
map_cut_2      0.150000    0.150000
map_cut_5      0.175000    0.175000
success_1      0.200000    0.200000
success_2      0.400000    0.400000
success_5      0.600000    0.600000

**Accuracy values per each test team (Utility)**

In [16]:
import pandas as pd
pd.read_csv('../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.utility.instance.csv')

,P_1.before,P_2.before,P_5.before,recall_1.before,recall_2.before,recall_5.before,ndcg_cut_1.before,ndcg_cut_2.before,ndcg_cut_5.before,map_cut_1.before,...,recall_5.after,ndcg_cut_1.after,ndcg_cut_2.after,ndcg_cut_5.after,map_cut_1.after,map_cut_2.after,map_cut_5.after,success_1.after,success_2.after,success_5.after
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,...,0.0,0.0,0.00000,0.00000,0.0,0.00,0.000,0.0,0.0,0.0
1,1.0,0.5,0.2,0.5,0.5,0.5,1.0,0.61315,0.61315,0.5,...,0.5,1.0,0.61315,0.61315,0.5,0.50,0.500,1.0,1.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.00000,0.0,...,0.0,0.0,0.00000,0.00000,0.0,0.00,0.000,0.0,0.0,0.0
3,0.0,0.0,0.2,0.0,0.0,0.5,0.0,0.00000,0.26407,0.0,...,0.5,0.0,0.00000,0.26407,0.0,0.00,0.125,0.0,0.0,1.0
4,0.0,0.5,0.2,0.0,0.5,0.5,0.0,0.38685,0.38685,0.0,...,0.5,0.0,0.38685,0.38685,0.0,0.25,0.250,0.0,1.0,1.0

**2. Running Adila (Bulk)**

To run on multiple prediction files in `parallel`, common for cross-fold validations of recommender models, `data.fpred` can be a folder cotaining the `*.pred` files related to the same dataset like:

```
acceleration='cpu' # all cores but one, or 'cpu:4' for four cores only
data.fpred=../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/
```

In [18]:
!python main.py data.fpred=../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/ "fair.algorithm=[fa-ir]" "fair.notion=[eo]" "fair.attribute=[popularity]" "fair.is_popular_alg=[avg]"

[2025-12-10 04:44:43,015][adila][INFO] - Loading stats, ratios, and ids for minority experts ...
[2025-12-10 04:44:43,020][__main__][INFO] - Queuing all *.pred files at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/ for popularity.eo.avg ...
/content/adila/src/adila.py:102: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  preds = torch.load(fpred, map_location='cpu')['y_pred']
[2025-12-10 04:44:43,023][adila][INFO] - Reranking ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f1.test.pred using fa-ir with 5 cutoff ...
[2025-12-10 04:44:43,024][adila][INFO] - Loading reranked file ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f1.test.pred.fa-ir.avg.10.5.rerank.pred for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f1.test.pred if exists ...
[2025-12-10 04:44:43,024][adila][INFO] - No existing rerank version. Reranking ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f1.test.pred ...
[2025-12-10 04:44:43,024][pkgmgr][INFO] - fairsearchcore not found.
[2025-12-10 04:44:43,024][pkgmgr][INFO] - Installing fairsearchcore...
[2025-12-10 04:44:46,580][pkgmgr][INFO] - Collecting fairsearchcore@ git+https://github.com/fani-lab/fairsearch-fair-python.git
  Cloning https://github.com/fani-lab/fairsearch-fair-python.git to /tmp/pip-install-v1tlt6y4/fairsearchcore_60f7e9fe27a84905bf3134962701f119
  Resolved https://github.com/fani-lab/fairsearch-fair-python.git to commit 1649e423d378800c99a988437d66b6479001f92a
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.8/dist-packages (from fairsearchcore@ git+https://github.com/fani-lab/fairsearch-fair-python.git) (2.0.0)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.8/dist-packages (from fairsearchcore@ git+https://github.com/fani-lab/fairsearch-fair-python.git) (1.10.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.23->fairsearchcore@ git+https://github.com/fani-lab/fairsearch-fair-python.git) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.23->fairsearchcore@ git+https://github.com/fani-lab/fairsearch-fair-python.git) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.23->fairsearchcore@ git+https://github.com/fani-lab/fairsearch-fair-python.git) (2025.2)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.23->fairsearchcore@ git+https://github.com/fani-lab/fairsearch-fair-python.git) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas>=0.23->fairsearchcore@ git+https://github.com/fani-lab/fairsearch-fair-python.git) (1.16.0)
Building wheels for collected packages: fairsearchcore
  Building wheel for fairsearchcore (setup.py): started
  Building wheel for fairsearchcore (setup.py): finished with status 'done'
  Created wheel for fairsearchcore: filename=fairsearchcore-1.0.4-py3-none-any.whl size=11596 sha256=a4ef80efedfcf1e24b32540dda213b6f12ef3424fd917755d82904ef7c6cca38
  Stored in directory: /tmp/pip-ephem-wheel-cache-cwpdfnuq/wheels/d1/74/c3/f9baeb6bd3c865ed524752365d9800a8fd82b7e71b312bf910
Successfully built fairsearchcore
Installing collected packages: fairsearchcore
Successfully installed fairsearchcore-1.0.4

/usr/local/lib/python3.8/dist-packages/fairsearchcore/fair.py:165: UserWarning: Library has not been tested with values outside this range
  warnings.warn("Library has not been tested with values outside this range")
  0% 0/5 [00:00<?, ?it/s]/usr/local/lib/python3.8/dist-packages/fairsearchcore/fair.py:165: UserWarning: Library has not been tested with values outside this range
  warnings.warn("Library has not been tested with values outside this range")
 40% 2/5 [00:00<00:00, 14.07it/s]/usr/local/lib/python3.8/dist-packages/fairsearchcore/fair.py:165: UserWarning: Library has not been tested with values outside this range
  warnings.warn("Library has not been tested with values outside this range")
/usr/local/lib/python3.8/dist-packages/fairsearchcore/fair.py:165: UserWarning: Library has not been tested with values outside this range
  warnings.warn("Library has not been tested with values outside this range")
 80% 4/5 [00:00<00:00, 13.99it/s]/usr/local/lib/python3.8/dist-packages/fairsearchcore/fair.py:165: UserWarning: Library has not been tested with values outside this range
  warnings.warn("Library has not been tested with values outside this range")
100% 5/5 [00:00<00:00, 14.44it/s]
[2025-12-10 04:44:47,249][adila][INFO] - Fairness evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f1.test.pred.fa-ir.avg.10.5.rerank.pred using ['ndkl', 'skew'] with 5 cutoff ...
5it [00:00, 3745.58it/s]
[2025-12-10 04:44:47,260][adila][INFO] - Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f1.test.pred.fa-ir.avg.10.5.rerank.pred.eval.fair.mean/instance.csv.
[2025-12-10 04:44:47,268][adila][INFO] - Utility evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f1.test.pred.fa-ir.avg.10.5.rerank.pred ...
[2025-12-10 04:44:47,268][adila][INFO] - Before: Loading ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f1.test.pred.eval.mean.csv ...
[2025-12-10 04:44:47,269][adila][INFO] - Before: Loading ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f1.test.pred.eval.mean.csv failed! Evaluating from scratch ...
[2025-12-10 04:44:47,271][pkgmgr][INFO] - evl.metric not found.
[2025-12-10 04:44:47,271][pkgmgr][INFO] - Installing evl.metric...
[2025-12-10 04:44:47,334][adila][INFO] - ['P_1,2,5', 'recall_1,2,5', 'ndcg_cut_1,2,5', 'map_cut_1,2,5', 'success_1,2,5'] ...
[2025-12-10 04:44:47,342][evl.metric][INFO] - Building pytrec_eval input for 5 instances ...
100% 5/5 [00:00<00:00, 2526.69it/s]
[2025-12-10 04:44:47,356][adila][INFO] - Before: Saving ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f1.test.pred.eval.mean.csv ...
[2025-12-10 04:44:47,358][adila][INFO] - After: Evaluating ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f1.test.pred.fa-ir.avg.10.5.rerank.pred ...
[2025-12-10 04:44:47,360][adila][INFO] - ['P_1,2,5', 'recall_1,2,5', 'ndcg_cut_1,2,5', 'map_cut_1,2,5', 'success_1,2,5'] ...
[2025-12-10 04:44:47,366][evl.metric][INFO] - Building pytrec_eval input for 5 instances ...
100% 5/5 [00:00<00:00, 2909.48it/s]
[2025-12-10 04:44:47,376][adila][INFO] - After: Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f1.test.pred.fa-ir.avg.10.5.rerank.pred.eval.utility.mean.csv.
/content/adila/src/adila.py:102: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  preds = torch.load(fpred, map_location='cpu')['y_pred']
[2025-12-10 04:44:47,377][adila][INFO] - Reranking ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred using fa-ir with 5 cutoff ...
[2025-12-10 04:44:47,377][adila][INFO] - Loading reranked file ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.avg.10.5.rerank.pred for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred if exists ...
[2025-12-10 04:44:47,379][adila][INFO] - Fairness evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.avg.10.5.rerank.pred using ['ndkl', 'skew'] with 5 cutoff ...
5it [00:00, 3404.47it/s]
[2025-12-10 04:44:47,386][adila][INFO] - Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.fair.mean/instance.csv.
[2025-12-10 04:44:47,393][adila][INFO] - Utility evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.avg.10.5.rerank.pred ...
[2025-12-10 04:44:47,394][adila][INFO] - Before: Loading ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred.eval.mean.csv ...
[2025-12-10 04:44:47,399][adila][INFO] - After: Evaluating ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.avg.10.5.rerank.pred ...
[2025-12-10 04:44:47,400][adila][INFO] - ['P_1,2,5', 'recall_1,2,5', 'ndcg_cut_1,2,5', 'map_cut_1,2,5', 'success_1,2,5'] ...
[2025-12-10 04:44:47,406][evl.metric][INFO] - Building pytrec_eval input for 5 instances ...
100% 5/5 [00:00<00:00, 2636.27it/s]
[2025-12-10 04:44:47,415][adila][INFO] - After: Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f0.test.pred.fa-ir.avg.10.5.rerank.pred.eval.utility.mean.csv.
/content/adila/src/adila.py:102: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  preds = torch.load(fpred, map_location='cpu')['y_pred']
[2025-12-10 04:44:47,416][adila][INFO] - Reranking ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f2.test.pred using fa-ir with 5 cutoff ...
[2025-12-10 04:44:47,417][adila][INFO] - Loading reranked file ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f2.test.pred.fa-ir.avg.10.5.rerank.pred for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f2.test.pred if exists ...
[2025-12-10 04:44:47,417][adila][INFO] - No existing rerank version. Reranking ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f2.test.pred ...
/usr/local/lib/python3.8/dist-packages/fairsearchcore/fair.py:165: UserWarning: Library has not been tested with values outside this range
  warnings.warn("Library has not been tested with values outside this range")
  0% 0/5 [00:00<?, ?it/s]/usr/local/lib/python3.8/dist-packages/fairsearchcore/fair.py:165: UserWarning: Library has not been tested with values outside this range
  warnings.warn("Library has not been tested with values outside this range")
 40% 2/5 [00:00<00:00, 15.77it/s]/usr/local/lib/python3.8/dist-packages/fairsearchcore/fair.py:165: UserWarning: Library has not been tested with values outside this range
  warnings.warn("Library has not been tested with values outside this range")
/usr/local/lib/python3.8/dist-packages/fairsearchcore/fair.py:165: UserWarning: Library has not been tested with values outside this range
  warnings.warn("Library has not been tested with values outside this range")
 80% 4/5 [00:00<00:00, 16.91it/s]/usr/local/lib/python3.8/dist-packages/fairsearchcore/fair.py:165: UserWarning: Library has not been tested with values outside this range
  warnings.warn("Library has not been tested with values outside this range")
100% 5/5 [00:00<00:00, 16.55it/s]
[2025-12-10 04:44:47,723][adila][INFO] - Fairness evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f2.test.pred.fa-ir.avg.10.5.rerank.pred using ['ndkl', 'skew'] with 5 cutoff ...
5it [00:00, 4285.15it/s]
[2025-12-10 04:44:47,729][adila][INFO] - Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f2.test.pred.fa-ir.avg.10.5.rerank.pred.eval.fair.mean/instance.csv.
[2025-12-10 04:44:47,736][adila][INFO] - Utility evaluation for ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f2.test.pred.fa-ir.avg.10.5.rerank.pred ...
[2025-12-10 04:44:47,736][adila][INFO] - Before: Loading ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f2.test.pred.eval.mean.csv ...
[2025-12-10 04:44:47,736][adila][INFO] - Before: Loading ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f2.test.pred.eval.mean.csv failed! Evaluating from scratch ...
[2025-12-10 04:44:47,738][adila][INFO] - ['P_1,2,5', 'recall_1,2,5', 'ndcg_cut_1,2,5', 'map_cut_1,2,5', 'success_1,2,5'] ...
[2025-12-10 04:44:47,743][evl.metric][INFO] - Building pytrec_eval input for 5 instances ...
100% 5/5 [00:00<00:00, 3335.70it/s]
[2025-12-10 04:44:47,749][adila][INFO] - Before: Saving ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f2.test.pred.eval.mean.csv ...
[2025-12-10 04:44:47,750][adila][INFO] - After: Evaluating ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f2.test.pred.fa-ir.avg.10.5.rerank.pred ...
[2025-12-10 04:44:47,751][adila][INFO] - ['P_1,2,5', 'recall_1,2,5', 'ndcg_cut_1,2,5', 'map_cut_1,2,5', 'success_1,2,5'] ...
[2025-12-10 04:44:47,757][evl.metric][INFO] - Building pytrec_eval input for 5 instances ...
100% 5/5 [00:00<00:00, 3395.65it/s]
[2025-12-10 04:44:47,764][adila][INFO] - After: Saved at ../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/popularity/eo/f2.test.pred.fa-ir.avg.10.5.rerank.pred.eval.utility.mean.csv.